package com.intellidine.common.exception;

public enum ErrorCode {
    VALIDATION_ERROR,
    INVALID_REQUEST,
    USER_NOT_FOUND,
    USER_ALREADY_EXISTS,
    AUTHENTICATION_FAILED,
    ACCESS_DENIED,
    RESOURCE_NOT_FOUND,
    RESOURCE_ALREADY_EXISTS,
    CONFLICT_ERROR,
    DATABASE_ERROR,
    EXTERNAL_SERVICE_ERROR,
    INTERNAL_SERVER_ERROR
}
