server:
  port: ${PORT:${SERVER_PORT:9090}}

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:restaurants_db}}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgrespassword}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

logging:
  level:
    root: INFO
    com.intellidine: DEBUG
